### ISSUE TITLE
Unable to select orthograpic view, context menu disappears

### ISSUE THREAD

**Issue by jayrulez** [FlaxEngine/FlaxEngine#10]
**Issue description:**

I'm unable to select the orthographic view in the scene view.
The context menu disappears when I try to navigate to the menu item to select the checkbox.

**Comment by jayrulez** [comment]
Ok, I was able to select it by carefully moving the mouse down the side of the context menu before selecting the menu item.

This seems to be another hitbox/hidpi issue.

**Comment by stefnotch** [comment]
I can reproduce this issue with the `View` menu in the Editor as well. This does not seem to be a highdpi issue but rather something that happens when a child context menu gets closed. (To debug: Set a breakpoint in the https://github.com/FlaxEngine/FlaxEngine/blob/ae665f9e6906dd577a0ec07ee97d41e40c2967ea/Source/Editor/GUI/ContextMenu/ContextMenuBase.cs#L191 function)

![image](https://user-images.githubusercontent.com/10220080/102696495-12b9e180-422f-11eb-959d-fc2e7d560c07.png)

**Comment by nocxtious** [comment]
Can confirm this is happening to me on any child context menu in the editor, not only in the View menu.  IE: right click an asset in the asset window and hover/mouse over "new" then move off, the whole menu closes.  Same for right clicking in the scene hierarchy window and moving over "new" and then off again.

**Comment by stefnotch** [comment]
Turns out that this was indeed a high dpi issue! When the child menu gets closed, it checks if the mouse is over the parent menu. But that check failed when you had a high dpi...
