### ISSUE TITLE
Restructuring of the UI system

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1126]
_I used the Unreal Engine Widget Blueprint as a base and tried to create a UI Graph without deviating too much from the Flax pattern_

**UI WorkFlow using this system**

1. You have to create a widget
![1-CreatWidget!](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/1c877cd2-69db-492a-a22f-a15d79cdab53)

2. Then rename it
![2-RenameWidget](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/0a80b878-47b4-403c-a382-1e74a7047db1)

3. Open your Widget and customize it to your liking. In this example I used the UIControl Panel and UIControl Label

**Important:**
- The UIControls and the other Widgets will be listed in the UI Library and you don't need to set the UIControl's type
- The Root of the Visual Tree is the Grid and is responsible for the size of your Widget and it has the UIControl CanvasScaler
![3-WindowWidgetNewGridScript](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/016acaa5-7bb2-4d33-9fd5-cb061da3f014)

4. Create a UI Canvas in your scene and in Render Mode change it to Screen Space
![4-CreateUICanvas](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/2803eafd-8281-40ad-9340-7f35efa60473)

5. DragDrop your Graph Widget to your Canvas UI widget parameter
![5-DragWidget](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/b2eb25a5-b8e2-4dc1-9e0c-99492d30a050)

6. Done, just play your game

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/948a3d0b-4a0d-4878-aaf2-fbd23659835c

**Change UI Parameters in RealTime**

- In Unreal engine to change the parameters of your UI components it is necessary to mark them as IsVariable = true;
To obtain the reference and be able to change them.

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/652174cf-36d6-4d47-a24c-8d6ff217493d

- At Flax I thought of these 2 options:

**Option number one: It's similar to the Unreal engine**

1. In your Wiget Graph go to your Hierarchy and select your UI Control you want to change
In this example it will be with the UI Control Label
![6-WidgetLabel](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/3f494189-cdb5-4e62-ac44-98722dc50697)

2. Change the name and check IsVariable = true;
After making the changes click on "Saved" to recompile your UI Canvas Widget
_Remembering that the name has to be unique for each UI Control/Widget_
![7-WidgetEditGeneral](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/a8cea0d4-482c-4bf6-b7f7-3fa5ff2523c2)

3. Create a Script for your UI Canvas similar to this one
```csharp
using System;
using System.Collections.Generic;
using FlaxEngine;
using FlaxEngine.GUI;

public class UI : Script {

    public UICanvas canvas;

    public override void OnStart()
    {
        if(!canvas) return;
        canvas.widget.TextTest.Get<Label>().Text = "Hello World";
    }
}
```

4. DragDrop your script on your UI Canvas
![8-DragScriptCanvas](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/d2a8bc19-477a-4598-abff-41daf1eb86ea)

5. Done, just play your game

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/ffdfe2c4-be98-404d-bdfc-ce0593037ca8

**Option number two: It's similar to Stride/O3DE**

1. This way is simpler just create your script and change it
```csharp
using System;
using System.Collections.Generic;
using FlaxEngine;
using FlaxEngine.GUI;

public class UI : Script {

    public UICanvas canvas;
    private UIControl controllText;

    public override void OnStart()
    {
        if(!canvas) return;
        controllText = canvas.widget.Find("TextTest");
        controllText.Get<Label>().Text = "Hello World";
    }
}
```

2. Then DragDrop your Script in your UICanvas and you can play your game
![8-DragScriptCanvas](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/a674327b-bedd-4d5c-8e68-3b295e110319)

**New instance of a Widget within another Widget**

- In Unreal Engine we can add a new instance of a Widget inside another Widget Blueprint
- And we can still change its parameters that are marked with IsVariable = true;

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/60feb129-0b74-4344-bc96-053d08cae149

- In the Flax engine it would look like this in your script using option number one
```csharp
using System;
using System.Collections.Generic;
using FlaxEngine;
using FlaxEngine.GUI;

public class UI : Script {

    public UICanvas canvas;

    public override void OnStart()
    {
        if(!canvas) return;
        canvas.widget.TextTest.Get<Label>().Text = "Hello World";
        
        canvas.widget.UICube.TextBlock_46.Get<Label>().Text = "Circle"; // New Line
    }
}
```

- In the Flax engine it would look like this in your script using option number two
```csharp
using System;
using System.Collections.Generic;
using FlaxEngine;
using FlaxEngine.GUI;

public class UI : Script {

    public UICanvas canvas;
    Widget widget;

    public override void OnStart()
    {
        if(!canvas) return;
        controllText = canvas.widget.Find("TextTest");
        controllText.Get<Label>().Text = "Hello World";
        
        widget = canvas.widget.FindWidget("UICube");
        widget.Find("TextBlock_46").Get<Label>().Text = "Circle"; // New Line
    }
}
```

**Important:** With this system it will no longer be possible to add UIControl children to UICanvas
Any other child can be added normally just the UIControl that doesn't
![9-NotChildUIControll](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/16e44a4a-3a53-46c9-98e9-128087dd778b)

- In general, you will need to change the UI Canvas and create the Widget Graph
- The scene and the prefab continued to work the same in relation to UICanvas

**Advantages of using this UI Graph/UI Editor system:**
1. There will be a separate UI editor making the engine cleaner
2. You will no longer have a big list of UIControl children in your scene
![10](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/aab7ef1f-d52b-40e7-ada4-738646e68521)

3. You no longer need to create a list for the UIControl or create a variable for each one
```csharp
public UIControl[] controls;
public UIControl control1;
public UIControl control2;
public UIControl control3;
public UIControl control4;
public UIControl control5;
public UIControl control6;
public UIControl control7;
public UIControl control8;
public UIControl control9;
```

4. You can filter by Widgets in Content
![11](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/a21c18ef-5b8c-43f6-8ac7-35a151526416)

5. Allows you to add a new instance of another Widget Graph inside another Widget Graph.
6. It allows changing the UICanvas widget in Real Time as it is done when changing the model of an actor
```csharp
using System;
using System.Collections.Generic;
using FlaxEngine;
using FlaxEngine.GUI;

public class UI : Script {

    public UICanvas canvas;
    public Widget widget;

    public override void OnStart()
    {
        if(!canvas || !Widget) return;
        canvas.widget = widget; // New Line
    }
}
```

7.  Creating your UI will be faster since you won't need to define the type of UI Controll, just DragDrop the desired UI Controll that is in the list on the left at the top inside your Widget Graph

**The use of the UI in Flax is currently kind of bad to work with these changes will make the workflow simpler and will have a more complete UI**

This UI Graph system works with Flax because it has a Material Graph/Particle Graph and now it would also have a UI Graph

**Common questions:**

1. What would a widget be?
- The widget is a file, just like the files you create for materials, particles, and so on.

2. Why use this term Widget?
- I used the term Widget as an example, Flex has to have a unique name. I thought about using UIGraph

3. Why use assets instead of prefabUI?
**The idea of PrefabUI is almost the same as that of a new Asset. It would be more correct to make it an asset. Prefab would be worse in my opinion because it would have to deal with many things like for example:**

- How will the prefab behave in the editor scene?
- Prefab is just created by DragDroping to Content before being just an Actor.
- How would the communication between PrefabUI and Prefab be?
- Who would be the root of PrefabUI and what children could it have?
- What would creating those children look like because having to use the new tab to add a new UIControl is kind of annoying. It's easier to drag and drop when the UIControl is listed in the UI editor
![Captura de Tela (150)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/26b5b985-7faa-4958-8022-83f3f288ae72)

**Analyzing some comments, the most correct option to obtain the reference of the UIControl in the Widget would be this** `Canvas.widget.FindOnWidget<Button>("button name");`
https://github.com/FlaxEngine/FlaxEngine/issues/1126#issuecomment-1565604681

**Comment by Tryibion** [comment]
A few of thoughts...

1. Needs a name other than widgets. maybe something like `UIControlContainer` or something else unique to Flax.
2. I do like the ability to reference parts by outside by having something like the `isvariable` bool, but I think it should support putting scripts on any control you want inside of the asset (similar to a prefabed control).
3. How would variables on each control be easily changed for debugging purposes when playing the game?

**Comment by RuanLucasGD** [comment]
flax's UI components are interesting, it has a lot of styling features. **but its usability makes me cry :X**

I also think it needs a separate editor, here are my ideas...

**I don't think it's viable to have a system to turn UI elements into variables for several reasons:**

* What would it be like to debug this?
* This would require a complex code generation system for the UI classes, what are the benefits of this other than not having to create variables for the elements? What if I try to rename something? Can all code break?
* I can't put scripts for UI elements, I would have to have an outside actor that had to access the element.

**What I like about your system:**

* Having a separate editor is much better than having UI elements mirrored by the scene, and this is something I've always hated with all my might in unity, I hope flax doesn't do the same.

**What I don't like about flax's UI system:**

* All UI elements are UIcontrol, this makes it a lot of work to maintain in the code, why do I need to do checks for each UIcontrol if the user (any developer that uses my system) has not added a wrong component to the Script properties.
* I don't have an editor for the UI.
* The UI is mounted in the scene, which creates clutter.

**My ideas for a new UI system without straying from what flax is:**

* Don't let create UI elements in the scene, let the user create a Prefab of the UI type (A custom actor just for UI)
* This allows you to have flexibility, add scripts in UI elements normally.
* Since it is a UI-specific prefab, add an editor, similar to the default prefab editor but with some options to help assemble the UI more easily

**Comment by RuanLucasGD** [comment]
Another point I hadn't thought of before about using `IsVariable `in the UI system:

It would not be possible to use in C++, and would require another way around this problem

**Comment by RuanLucasGD** [comment]
If using an Assets system, searching for UI elements by c++/c# code could be by name. Example:

`Canvas.FindOnWidget<Button>("button name);`

**Comment by PhyresiCompany** [comment]
> Algumas reflexões...
> 
> 1. Precisa de um nome diferente de widgets. talvez algo parecido `UIControlContainer`ou algo exclusivo do Flax.
> 2. Eu gosto da capacidade de fazer referência a partes fora do ativo por meio de algo como o `isvariable`bool, mas acho que deve oferecer suporte à colocação de scripts em qualquer controle que você deseja dentro do ativo (semelhante a um controle pré-fabricado).
> 3. Como as variáveis ​​em cada controle seriam facilmente alteradas para fins de depuração durante o jogo?
> 4. Além da parte do editor, como isso é diferente de apenas criar um prefab de alguns arquivos `UIControls`. Talvez uma criação de controle mais fácil? Seria melhor criar um editor pré-fabricado especial ou melhorar o existente para interface do usuário e `UIControls`?

@Tryibion 
1. I used the Widget as an example, I agree that Flex has to have a unique name. What do you think of UIGraph?
2. An alternative to get the reference would be to allow adding a script at the root of the UI, which is the Grid, but you could get them without using the Get<> of the UIControl, only you would have to create a new script for the UI
![gridd](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/f8fdbe71-4610-427c-8577-6429814883ab)

```csharp
using FlaxEngine;
using FlaxEngine.GUI;

public class UI : UIGraph
{
    public Label text;

    public override void OnStart()
    {
        text.Text = "Example";
    }
}
```

3. When clicking on "Save", the UI will be compiled, if any error occurs in this compilation, the Compile results tab of the UI itself will be displayed
![error2](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/43e2d173-79e4-403e-aed2-00c7063752e7)

If the error is in your code, it will be displayed normally in Flax's DebugLog
![Captura de Tela (149)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/77531722-f303-458c-a65e-72dcafc193c6)

4. **Prefab would be worse in my view because of these reasons:**
- How will the prefab behave in the editor scene? Prefab is only created by DragDroping to Content before it is just an Actor
- How would the communication between PrefabUI and Flax's normal Prefab be?
- Who would be the root of PrefabUI and which children could he have?
- How would the creation of these children be, why having to use the new tab to add a new UIControl is kind of bad. It is easier to DragDrop when the UIControl is listed in the UI Editor
![Captura de Tela (150)](https://github.com/FlaxEngine/FlaxEngine/assets/101017436/bc291683-7a49-4b41-b7d4-d4437bf6a3d2)


_The idea of PrefabUI is almost the same as that of a new Asset. It would be more correct to make it an asset_

**Comment by RuanLucasGD** [comment]
@PhyresiCompany I agree, I hope it is then possible to have an Asset, but I hope that the asset can have scripts attached to the UI elements, for example a button with its own script.

**Comment by RuanLucasGD** [comment]
@mafiesto4 If it is possible to have an asset-based UI system, would it be possible to have scripts attached inside the UI elements in that asset? Similar to UIcontrols, which are basically actors.

**Comment by mafiesto4** [comment]
I like this idea of asset-based widgets and actually, that's exactly what I wanted to achieve with **UI+Prefabs combo** :)

The only thing is that `UIControl` actor is kind of essential for UI creating fro ma single controls. Maybe `UI Control Container` would be good here? So that actor could use a whole structure (aka widget) of Controls?

Finally, UI styling is a kind of important topic to cover too. Initially, I was thinking that users can create prefabs of UI controls base (eg. `GameButton.prefab`) with styling setup (colors, fonts, etc.) which can be reused in more complex UI interfaces - by empowering prefabs its easier to update whole UI just by editing base prefab.

Here are some ideas to improve Prefab Editor when editing UI that we should do:
* disable the sky background and add 2D grid background
* add transform widgets for easy anchors setup and controls resizing inside the prefab view
* remove Transform group - let use Controls' Transform editor only

I added this task to the Flax 1.7 roadmap so we can tackle UI Improvements in that update.

**Comment by PhyresiCompany** [comment]
> I like this idea of asset-based widgets and actually, that's exactly what I wanted to achieve with **UI+Prefabs combo** :)
> 
> The only thing is that `UIControl` actor is kind of essential for UI creating fro ma single controls. Maybe `UI Control Container` would be good here? So that actor could use a whole structure (aka widget) of Controls?
> 
> Finally, UI styling is a kind of important topic to cover too. Initially, I was thinking that users can create prefabs of UI controls base (eg. `GameButton.prefab`) with styling setup (colors, fonts, etc.) which can be reused in more complex UI interfaces - by empowering prefabs its easier to update whole UI just by editing base prefab.
> 
> Here are some ideas to improve Prefab Editor when editing UI that we should do:
> 
> * disable the sky background and add 2D grid background
> * add transform widgets for easy anchors setup and controls resizing inside the prefab view
> * remove Transform group - let use Controls' Transform editor only
> 
> I added this task to the Flax 1.7 roadmap so we can tackle UI Improvements in that update.

@mafiesto4 

Thank you very much. A widget asset resource and UI editor system will be amazing for UI usability and for UI controls

**Comment by kiririn39** [comment]
Hi guys. 
Sorry for a bit late comment, but as of now this issue is still open so i think its kind of ok to add to this discussion my own opinion.
I'm not sure if i correctly understood all benefits of new ui system.
Unreal in general has a lot of bad designs and ui system is one of them. Unity has far more superior approach imo. I have worked with both of them and here are my points:
1. having a semi-separate window for ui editing is a good thing imo
2. this one is a major one. I's separate it in two:

2.1. The problem with clutter exists only for editor. It's kind of a developer responsibility to structure their ui hierarchy in a reasonable way. Not to mention you can always just minimize the ui branch or root entirely. It's a general "problem" for a game engine. You'll end up with hundreds of entities anyway. it wont save the day by removing part of it (ui tree)

2.2. Having any node tree compacted to a single one creates a "black box" object. No matter if its an ui or any other system. Which is super bad decision imo. 
How you supposed to inspect or change entities inside it? Should you make a separate ui hierarchy window for it? But then what's the point in doing so? you'll be cutting out hierarchy branch from one window and pasting it to another window?  I dont see the merits.
Lastly, are you sure you want to treat ui entities and other entities(mesh or lighting)? Maybe developers will be making a ui centric game or something. In such a case they will spend most of their time in this new ui hierarchy window but again for what reason if they can threat ui elements and non ui in same way. Basically client developers should decide what is "game entity" and what is ui. Enforcing specific point of view on what is what (for a general purpose system) from engine side is kind of.. naive? By having transparent ui hierarchy you can move branch from a canvas in to another canvas or maybe not in a canvas at all. 

2.3 This still could be a thing for a system where ui is something completely different like having html engine markup, for performance reasons or something. In that case that would make more sense to wrap it up in a single 'black box' item. 

3. Put them in array and use virtual calls? what type of entity are you making? if its a scrollbox array would suffice? If its was a complex ui element than i would make a layered abstractions. Yeah it a bit oop heavy but it still a good option for uis

5 and 6 i dont really get. Cant you just spawn new ui branch inside another branch? Or delete or move. I think it counts as "changing behavior on the fly" 

Anyway, excuse me for this wall of text. Opinions my own from my own experience. No offense, just want to have a healthy discussion on this topic.

**Comment by RuanLucasGD** [comment]
@kiririn39 I agree with you, as much as I find it horrible to edit the UI in the game itself, I also believe that transforming the entire UI structure into a separate element can bring several problems. 

If the entire UI is a specific asset apart from the entire scene, it will be necessary to recreate the entire entity structure system just for the UI, which can be very bad.

This could also limit interaction with 3D scene elements within the UI.

Anyway, I hope it's possible to have a good separate UI editor without compromising the scene structure

**Comment by NoriteSC** [comment]
Done some experimenting 
and tried to implement the idea but there are problems the current underlying UI system can support it in some way.
the unreal system as u given as a example is designed with assets in mind

the problems are
how to actually parent Asset Controls together in scene / editor
the navigation system will be broken
u can't add scripts to controls
how this will work with multiplayer
if u need to sync color for example
backwards compatibility bites a lot
serialized file problems because of backwards compatibility
detecting dynamic objects so there are not saved to file

**Comment by mafiesto4** [comment]
![ui_editor_resizing_widget](https://github.com/user-attachments/assets/e552c5d6-aa33-4eb7-94e7-975dc61d4975)

Flax 1.8 contains new visual UI Editor (inside Prefabs and partially in Game window). In Flax 1.9 we will be adding more functionalities for creating Widget Prefabs that are targeting UI workflow.

Thanks for all your discussion that helped develop the new UI. Feel free to open new issues for further discussion, suggestions or bug reports.
