### ISSUE TITLE
Bug with AnimGraphParameter in Release Builds

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#121]
There is an issue with the AnimGraphParameter and Release Builds.

Basically, the AnimGraphParameters work fine in the Editor but they fail to cook in the release build. Here is a side-by-side comparison of it not finding the parameter.

![image](https://user-images.githubusercontent.com/35228400/105156764-5ec6b180-5b60-11eb-932f-1cb4f1aa2862.png)

You can download a copy of my test project here. Just cook the game project to see the issue for yourself: https://drive.google.com/file/d/1wgQObzXkD856_RlsNzBH0YRG_d2PfM1J/view?usp=sharing

**Comment by mafiesto4** [comment]
The problem was missing `WaitForLoaded` call on `AnimationGraph` asset which ensures the AnimatedModel has valid instanced graph parameters list. Fixed in: https://github.com/FlaxEngine/FlaxEngine/commit/8dce3c0fb76b7dc35abe9fd8cdc81605cb315d2e

As a temporary workaround you can also add sth like this in your script:
```cs
// Ensure asset is loaded before accessing it
Actor.GetChild<AnimatedModel>().AnimationGraph.WaitForLoaded();

// Now access parameter
AnimSpeed = Actor.GetChild<AnimatedModel>().GetParameter("Running");
```

**Comment by mafiesto4** [comment]
Cool project by the way! 💯
