### ISSUE TITLE
Infinite Grid

### ISSUE THREAD

**Issue by PhyresiCompany** [FlaxEngine/FlaxEngine#1227]
The grid has a maximum size. Ideally, it should be infinite and rendered according to the editor camera position.

https://github.com/FlaxEngine/FlaxEngine/assets/101017436/9586d715-9c2f-41cd-aea7-e96810ce9cdd

**Comment by Arcnor** [comment]
For anybody attempting this, there is an excellent tutorial I've used many times here https://asliceofrendering.com/scene%20helper/2020/01/05/InfiniteGrid/ . It uses a single pass shader instead of drawing separate lines, so it's probably more complex than the existing solution, but the end result is neat, specially if the last optional fade step is implemented.

**Comment by SinnersSum** [comment]
Infinite grid sounds like a nice addition, currently too dark in the area it occupies (overdraw) and it ends far too soon.

**Comment by mafiesto4** [comment]
Added in #2663
