### ISSUE TITLE
Editor Crashes when trying to use Make a Custom Editor From another Module

### ISSUE THREAD

**Issue by InnovativeName-GameDev** [FlaxEngine/FlaxEngine#1255]
**Issue description:**
I was experimenting with Custom Editors and Custom Editor Windows, but because i don't wont to have conditional compilation everywhere i decided to use a secondary module with the Game Module (the module with all of the game logic) as a public dependency. When i recompile the code, it crashes, because of the Custom Editor stuff. 
The Log file
[Log_2023_07_19_08_23_45.txt](https://github.com/FlaxEngine/FlaxEngine/files/12091768/Log_2023_07_19_08_23_45.txt)

**Steps to reproduce:**
Use the Linked Project in the Zip file, open the Project, and Recompile code.
(Maybe test on linux)

**Minimal reproduction project:**
[crash_with_custom_editor.zip](https://github.com/FlaxEngine/FlaxEngine/files/12091777/crash_with_custom_editor.zip)

**Flax version:**
Flax version: 1.6.6344

**Comment by Tryibion** [comment]
Looks like the editor is crashing due to you having the `[CustomEditor(typeof(DataClassLibrary))]` above your custom editor window... This is not how it is done. If you read this example: <https://docs.flaxengine.com/manual/scripting/tutorials/custom-window.html> you have to do something like this:
`
    [CustomEditor(typeof(DataClassLibrary))]
    public class DataClassLibraryEditor : GenericEditor
    {
        public override void Initialize(LayoutElementsContainer layout)
        {
            base.Initialize(layout);
            var button = layout.Button("Click Me", Color.Green);
            button.Button.Clicked += () =>
            {
                new CustomEditorOfDataClassLibrary().Show();
            };
        }
    }
    
    public class CustomEditorOfDataClassLibrary : CustomEditorWindow
    {
        public override void Initialize(LayoutElementsContainer layout)
        {
            var button = layout.Button("Click me", Color.Green);
        }
    }
`

**Comment by AtomicBlom** [comment]
I don't think you're incorrect that the annotation should be on the GenericEditor instead of the CustomEditorWindow, but I think that might actually be a red herring.

I've been struggling with my Flax editor crashing for the past couple hours with the exact same error, the one difference though is that I'm not using custom windows, but I am trying to use a separate module for the editor code.

I've also provided a minimal sample that exhibits the crash.

Steps to reproduce:
Use the Linked Project in the Zip file, open the Project, and Recompile code.

Flax Version: 1.6.6344
Platform: Windows 11

Project: [MyProject.zip](https://github.com/FlaxEngine/FlaxEngine/files/12206699/MyProject.zip)
Logs: [Log_2023_07_29_18_19_22.txt](https://github.com/FlaxEngine/FlaxEngine/files/12206703/Log_2023_07_29_18_19_22.txt)

**Comment by Tryibion** [comment]
Yeah, there is some issue there.
