### ISSUE TITLE
Dividing 1 by 2 in shader graph returns 0

### ISSUE THREAD

**Issue by Muzz** [FlaxEngine/FlaxEngine#1472]
**Issue description:**
dividing any number by a number that is larger than itself should return a fraction, but at the moment it just returns 0. 

![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/01b4dcde-8dd7-437f-811b-c69f59e963c5)

I'd expect this to be the output. 
![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/966f13d3-e19d-457c-8718-596afa6abe82)

**Steps to reproduce:**
Make a shader, divide 2 by 1 and pass it into the material. 

**Flax version:**
master

**Comment by Muzz** [comment]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/2074204/a92fd3de-bfa9-4bf8-ab65-7b397725a80b)

This is my terrible work around atm.

**Comment by MineBill** [comment]
The problem lies here:
https://github.com/FlaxEngine/FlaxEngine/blob/da7ba0ecbaa33313558cb16da793db7017bfaa6c/Source/Engine/Visject/ShaderGraph.cpp#L1172C1-L1177C2

Basically, the string representation of the floating number only includes the fractional part if it's not zero. As such, the generated code looks like `1 / 2` which an integer division. My initial thought was to always cast the numbers to their types:
```c++
const Char* typeStr = ValueTypeToString(valueA.Type);
const String value = String::Format(TEXT("({3}){0} {1} ({3}){2}"), valueA.Value, op1Str, Value::Cast(valueB, valueA.Type).Value, typeStr);
```
but even though it works (i've tested this locally), i'm not sure it's the best idea.

**Comment by MineBill** [comment]
Actually, the fix is much simpler :^)
