### ISSUE TITLE
Objects or Gizmos not Selectable with Far Plane Value to high

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#1486]
**Issue Description:**
Unable to select objects or gizmos in editor view after setting editor camera far plane to 2,000,000. One million works. Probably 32-bit float precision. Probably not fixable/not worth fixing, but maybe at least warn/limit the Far plane to some always working numbers.

Why did I set it to 2,000,000? 
Just a random act of, \*grumble\* can't see far enough with 100,000, 2,000,000, should be enough forever^^ Bad Idea.

1,000,000 does work, but not reliable. Depending on the camera rotation, the gizmo is sometimes recognized and sometimes not.

**Steps to reproduce:**
Set Editor Far Plane to 2,000,000 or higher

**Minimal reproduction project:**
any project

**Flax version:**
1.6.6344

**Comment by RuanLucasGD** [comment]
This broken terrain gizmo too

**Comment by solnem** [comment]
Near/far plane is weird at the moment anyway

**Comment by NoriteSC** [comment]
>Unable to select objects or gizmos in editor view after setting editor camera far plane to 2,000,000. 

this is because selection is using project from screen to world and is using 2 of it 1 for neer place and 1 for far place and is calculaeting a direction for it and construct ethe mouse ray and the ray with point in the -direction of the mouse in world space
this can be fixed but because of limit how far the GPU can render the limiter will be better
