### ISSUE TITLE
Camera.MainCamera is null on OnAwake()

### ISSUE THREAD

**Issue by RuanLucasGD** [FlaxEngine/FlaxEngine#1598]
**Issue description:**
You cannot access main camera on OnAwake because the camera is only assigned to Cameras list on OnEnable of the Actor.
https://github.com/FlaxEngine/FlaxEngine/blob/167fead18d36c38ff1bc061201b1da4bf3440ff9/Source/Engine/Level/Actors/Camera.cpp#L436C14-L436C14

**Steps to reproduce:**
```
        public override void OnAwake()
        {
            Debug.Log(Camera.MainCamera);   // bad
        }

        public override void OnStart()
        {
            Debug.Log(Camera.MainCamera);   // ok
        }
```

**Flax version:**
1.6 master

**Comment by mafiesto4** [comment]
I'm not sure if we want to change this as `OnAwake` is called to mark object as loaded but not yet active in a game thus when loading scene the main camera (and other gameplay objects) might not be ready to use. That's why `OnAwake` should handle object-only setup - it's called when loading a scene that has not yet been added to `Level::Scenes` so changing it could open other issues.

**Comment by Tryibion** [comment]
Should this be mentioned in the docs about the purpose on OnAwake? Or is it already?
