### ISSUE TITLE
Backport bugfixes to current stable version of the engine.

### ISSUE THREAD

**Issue by Menotdan** [FlaxEngine/FlaxEngine#1727]
It is very important that the stable version of the engine have bugfixes from master backported to the older versions and having consistent releases. The majority of people use the stable version, and having bugs like that is a very bad look for the engine, as well as very bad for stability. Also, having to wait for bugfixes while still using a stable version of the engine is quite annoying. I suggest a system be created to allow for backporting of bugfixes to the current stable version of the engine.

**Comment by mafiesto4** [comment]
Yeah usually we do 1-3 hotfix updates after major release. We should do sth similar for `1.7`.

**Comment by Menotdan** [comment]
> Yeah usually we do 1-3 hotfix updates after major release. We should do sth similar for `1.7`.

I didn't get any hotfix updates during 1.6, and it seems neither did anyone else, as many people were having issues with 1.6, and ot seemed like `master` became the best version, which is bad IMO.

**Comment by mafiesto4** [comment]
Flax is a project that grows, we don't operate at scale of Unity, Unreal or Godot which can manage multiple active engine versions. But we will do our best to maintain better support for active versions since the userbase quickly grows :)

Here are some docs about Release Policy we have: https://docs.flaxengine.com/manual/contributing/release-policy.html
