### ISSUE TITLE
Prefabs: Breaking the Prefab Link on a Parent breaks every Child Prefab as well

### ISSUE THREAD

**Issue by madsfs** [FlaxEngine/FlaxEngine#1752]
If you have a Prefab and you child that to an Actor it will be childed correctly to that actor.
If you then make a Prefab out of that Parent it also becomes a Prefab as you'd expect.

However, if you choose to break the Prefab link of a Parent that also have child prefabs, then those child prefabs will also be broken, meaning that you now have a Parent Actor full of non-Prefab children.

This leaves the Prefab workflow as-is extremely limited.

**Comment by Menotdan** [comment]
Could you elaborate how the prefab workflow is limited by this? Do you have an example? I'm interested in having this resolved

**Comment by mads-fs** [comment]
> Could you elaborate how the prefab workflow is limited by this? Do you have an example? I'm interested in having this resolved

What it essentially means is that you can't have layers of prefabs. I can't make three separate prefabs (A, B and C), child them to a parent and make a prefab out of that which now consists of three separate prefabs (A + B + C). It becomes one new prefab (D).

That means that if I want to change one of the child prefabs, let's say A, and have the change apply to all instances it won't apply to D. Because it's not A+B+C, it's an entirely separate prefab D.

**Comment by mtszkarbowiak** [comment]
Any info on the issue?

**Comment by mafiesto4** [comment]
Added in f1b133bd6008b0c7e3acf4cf37e2458ec826fb33.
