### ISSUE TITLE
Game Script Modules Not Loading | ThirdParty File Not Being Found | Another small bug

### ISSUE THREAD

**Issue by vulcan-dev** [FlaxEngine/FlaxEngine#187]
**Issue description:**

Game script modules not loading, therefor the scene will not load. I excpected it to load my project without any issues like any C# project in the Flax Engine.

This also only happens when I use C++ as the scripting language.

Another issue is including PxTransform from <ThirdParty/...> inside of the IPhysicsActor.h file, it's unable to find it.

There's also another bug but it's only a small one, if you drag a file into the flax homescreen then it will output all the contents of that file inside of flax and you have to restart to get it back to normal.

**Steps to reproduce:**

- Create a project
- Make the scripting language C++ instead of C#
- Edit the script, for example make the camera follow a certain actor
- Exit out of Flax Engine and reload the project

**Minimal reproduction project:**

Unable to upload due to filesize.
ThirdParty Download: https://filebin.net/nlowcuqz9dq0q1js

**Flax version:**

1.0

**Comment by mafiesto4** [comment]
Thanks for reporting those!

1) I noticed 2 bugs in your code: `GetTarget()` method should return `Actor*` instead of `bool` (I added check for bindings generator to warn about it here https://github.com/FlaxEngine/FlaxEngine/commit/fb74aef541c18a0a55deee1b761ed0506d3cba31) and you should initialize `_target = nullptr` to prevent crashes (as C++ requires). With those changes, it works fine.

2) This `PxTransform` including issue has been fixed in https://github.com/FlaxEngine/FlaxEngine/commit/283714a39f4582c3d5d7cc849791be22ce95d330 and https://github.com/FlaxEngine/FlaxEngine/commit/1bd639c86df48f5dc56124e2f59e2c12eee01eaa

3) It's fixed and will be available in the next Launcher update. Also, the Projects page will accept incoming drag&dropo of Flax project file to add it to the list quickly.
