### ISSUE TITLE
Flax 1.7 Steam not initializing

### ISSUE THREAD

**Issue by getmyisland** [FlaxEngine/FlaxEngine#1873]
**Issue description:**
I want to use the Steam API in my game project, but I can't get Steam to recognize my Flax game, or my Flax game doesn't recognize Steam. With a simple Unity project with Steamworks.NET it was recognized immediately without any problems.

I tried 2 ways to initialize Steam:

1) The online method where I followed [this](https://github.com/FlaxEngine/OnlinePlatformSteam) tutorial. What should happen when starting the game is that Steam indicates that you are playing the Spacewar application (App Id 480). Instead, an exception is thrown by the online class (see log file line 232).

2) The Steam method where I referenced the Steamworks.NET library directly with [this](https://docs.flaxengine.com/manual/scripting/tutorials/use-third-party-library.html?q=third%20party) tutorial. Just like above, Steam should indicate that you are playing Spacewars. Instead, you just get an error message that SteamAPI could not be initialized.

Because it works with Unity and pure C# applications I suspect the issue may not be my fault right? There are some example projects below that replicate this issue at least on my computer.

[SteamTest_Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13257367/SteamTest_Log.txt)
[OnlineTest_Log.txt](https://github.com/FlaxEngine/FlaxEngine/files/13257371/OnlineTest_Log.txt)

**Steps to reproduce:**
Download one of the example projects below and enter Play mode **while** Steam is running in the background.

**Minimal reproduction project:**
[OnlineTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/13257351/OnlineTest.zip)
[SteamTest.zip](https://github.com/FlaxEngine/FlaxEngine/files/13257362/SteamTest.zip)

**Flax version:**
1.7

**Comment by mafiesto4** [comment]
1) You're missing step **5) Setup settings** from that tutorial so plugin uses `AppId=0` as `steam_appid.txt` file is managed by plugin automatically. I fixed this in a22d8d10bf13613b951dec0fb7c9d4c98dcc2481 to properly handle missing appId such this case. There was a bug caused by recent migration from Mono to .NET 7 where DLLs loading was a little off, I fixed it in c23f8f2b3015fc07195115e6248622a6741e9a5f. Now it works fine.

2) You're missing `steam_appid.txt` file, it says it in the Output when running project with native debugger inside Visual Studio:
```
[S_API FAIL] SteamAPI_Init() failed; no appID found.
```
After adding dummy appid file with 480 id it works fine.

Thanks fro reporting this!
