### ISSUE TITLE
Mesh collider not working on rigid body [Flax 1.7]

### ISSUE THREAD

**Issue by d1kkop** [FlaxEngine/FlaxEngine#1884]
Either create a basic template project (with blue cube) or download the link from [WeTransfer](https://wetransfer.com/downloads/b1eeafeec675dd5368ef7a92b475886120231106153650/0bf38c?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

Create a rigidbody. Add a model (cone). Click on the cone and r-mouse -> create collider. A mesh collider is saved to disk.
make collider a child of rigidbody so that both model and collider are a child of rigidbody. Same set up as the original blue cube.

Elevate the cone a bit so that when Play is pressed it drops down.
Result: falls through ground.
Expected: would hit ground.

Flax 1.7

![mesh_collider](https://github.com/FlaxEngine/FlaxEngine/assets/10207653/30faacfe-a91d-4da9-b808-9319a8354d06)

**Comment by RuanLucasGD** [comment]
Hello!

Your collider don't work because the Collider Type is setted to Triangle Mesh. Change it to Convex
![image](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/fc4a6d25-67fa-4d5e-8167-4d214e8d1783)

After this your physics works fine
![image](https://github.com/FlaxEngine/FlaxEngine/assets/79365912/26fe7249-4822-4a4e-bd13-71e70cd643b5)

**Comment by d1kkop** [comment]
Ok, thanks for the help.
