### ISSUE TITLE
Issue with c# network driver

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#1992]
**Issue description:**
Having an all c# network driver does not seem to work. I get this stack trace:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/71274967/7fad9c8a-7958-45e4-955c-5be4375aa844)

It looks like it is some issue with `NetworkConfig`.

**Steps to reproduce:**
Add a c# network driver to your project and change the type to it in the network settings. try starting a server (or anything that tries to initialize the network driver).

<https://github.com/Tryibion/FlaxFacepunchSteamworks/blob/main/Source/FacepunchSteamworks/FacepunchNetworkDriver.cs> <- There is a c# network driver here that I have been building that I get this error on.

**Flax version:**
1.7

**Comment by mafiesto4** [comment]
Crashes fixed in 39dc5939e3461ab1dca6c1de5ff564dbda69ed83 and fd938e8284177f1c6f28006bc1aee69f5adaa4fe but the current interface implementation was using raw pointer for PopEvent so for proper C#/VisualScript integration I had to refactor it into `out` parameter so it will be properly handled: 35ebdb0ffe5beabe4606db7b37b153c2e2af86ab and with some fixes for this: 8ffc86ef881d0c82ebea99111e19f71bbc243656 and a909b57e82cbf8eab155780e015da274ce9f5d91.
