### ISSUE TITLE
Global Sample SDF node returning wrong values in material graph.

### ISSUE THREAD

**Issue by Ryoskn** [FlaxEngine/FlaxEngine#2101]
**Issue description:**
Sample Global SDF Node returns odd results with visible artifacts despite model with applied material not being near other objects in proximity within the SDF sampling range. 
Sample Global SDF also returning no result on lower Global SDF qualities than High.

![image](https://github.com/FlaxEngine/FlaxEngine/assets/18261784/9d6ff4e2-7594-4904-9d56-cd5079dbf099)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/18261784/fcddc4ed-ebce-4d2b-8519-d6a22ba1a23d)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/18261784/a600c954-92f8-449f-827b-21da68dbcc19)

![image](https://github.com/FlaxEngine/FlaxEngine/assets/18261784/edf97b29-106d-4073-9378-fcbc3d5d7c4d)

**Minimal reproduction project:**
[(https://www.mediafire.com/file/mrqdflkyticm3qi/SampleSDFTest.7z/file)]

**Flax version:**
Stable Branch 1.7.1 as of 12/19/2023

**Comment by mafiesto4** [comment]
https://discord.com/channels/437989205315158016/1185218392651743344

**Comment by mafiesto4** [comment]
> Sample Global SDF Node returns odd results with visible artifacts despite model with applied material not being near other objects in proximity within the SDF sampling range.

If the object you're using material on is affecting GlobalSDF then you won't get so smooth results due to low-res representation of the scene geometry such as SDF. I would suggest using normal-based offset fro the object surface to sample GlobalSDF properly and get nice nearby values - eg. for procedural moss/snow/dirt placement in materials:

Also, SDF value contains distance which can be useful to nicely blend with some smoothing function, you can also sample SDF gradient for more complex interaction:


> Sample Global SDF also returning no result on lower Global SDF qualities than High.

Not true, Global SDF resolution is small on Low/Medium that your material is not being able to visualize it in that simple scene. Use it in a more complex world and you will see:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/c5be9a24-55b5-49a3-9549-a35c7007f34e)

**Comment by mafiesto4** [comment]
> Sample Global SDF Node returns odd results with visible artifacts despite model with applied material not being near other objects in proximity within the SDF sampling range.

If the object you're using material on is affecting GlobalSDF then you won't get so smooth results due to low-res representation of the scene geometry such as SDF. I would suggest using normal-based offset fro the object surface to sample GlobalSDF properly and get nice nearby values - eg. for procedural moss/snow/dirt placement in materials:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/58fafbdc-32d0-493f-9399-f96f819d1732)

Also, SDF value contains distance which can be useful to nicely blend with some smoothing function, you can also sample SDF gradient for more complex interactions:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/f15a4036-de62-40e7-aa73-a6b638e8d332)

> Sample Global SDF also returning no result on lower Global SDF qualities than High.

Not true, Global SDF resolution is small on Low/Medium that your material is not being able to visualize it in that simple scene. Use it in a more complex world and you will see:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/c5be9a24-55b5-49a3-9549-a35c7007f34e)
