### ISSUE TITLE
Three Seperate UI Bugs

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#218]
I've found three more UI Bugs. Please see this film:
https://drive.google.com/file/d/1LK7rcLKk5enwgJh05xy-fKWMQMLCIYTM/view?usp=sharing

**Steps to reproduce:**
I've recorded steps to reproduce two of the three but the first one is more difficult to reproduce.

**Minimal reproduction project:**
Current version in Github

**Comment by mafiesto4** [comment]
1) The first bug fixed in https://github.com/FlaxEngine/FlaxEngine/commit/58350c87e252502f8191589659374dcfbdb11daa - prefab preview was black because the viewport camera was teleported to the `Infinity` when doing automatic view snapping to see the whole actor while Character Controller had uninitialized bounds

**Comment by mafiesto4** [comment]
2. The second bug fixed in 8fb27e6f8399904d099f54d398a1b2a2a3752ccf - prefab preview was not linking the `UICanvas`, now it works fine when adding/removing canvas.

**Comment by mafiesto4** [comment]
3. The third bug fixed in 2a2d9f54dee7f0d8c3f012e2cec2879a768eddd0 - `UIControl` actor serialized `Transformation` property as it was modified compared to the prefab default instance but that's because different viewport size. However `Control.Location` is valid after deserialization cause it uses anchors and offsets which are view-size independent so updating the actor location fixes this problem.

**Comment by mafiesto4** [comment]
I also fixed a few other issues I found when working with this ticket (e6d3242670f1f49791b12d25f0ee44e36c5abe0e, 0122bf68bf5da371b397d324058acf318cbb16e7).
