### ISSUE TITLE
[Issue] Something wrong with DDGI

### ISSUE THREAD

**Issue by ElevenArt** [FlaxEngine/FlaxEngine#2281]
This issue happens when I change DDGI Bounce Intensity around 1.5 and more in Graphic Settings.

https://github.com/FlaxEngine/FlaxEngine/assets/154741707/1d4d8bc7-eac8-45a1-af33-73c2f1162c49

In this situation, I create PostFXVolume and I set DDGI Intensity to 0.1 and guickly toggle On/Off PostFXVolume

https://github.com/FlaxEngine/FlaxEngine/assets/154741707/d8ee5119-7b89-469d-8a43-d0023fb71028

Same is here, but with less intensity when I changed Temporal Response to 0.15 in Graphic Settings.

https://github.com/FlaxEngine/FlaxEngine/assets/154741707/5f63949a-4a61-49a5-aec1-e682d489ed3d

In this situation I turned off DDGI in PostFXVolume and there is no issues.

https://github.com/FlaxEngine/FlaxEngine/assets/154741707/a0c5b360-f07f-4506-9b7d-e7630a7b7430

Something is wrong here, but I have no idea why.
It seems to be something like an infinite Bounce light loop or something similar. Something that Temporal Response partially limits when switching quickly, but it looks like the 2 different images between default settings and PostFXVolume are mathematically Add when switching. Something like 2+2+2+2+2+2+2+2+2+2+2, etc.

Steps to reproduce:
I don't know what's going on here

Flax version:
Master Branch 26.2.2024

**Comment by ElevenArt** [comment]
Do you have any other shaders attached to your Bloom?

DDGI.hlsl file have these:
#include "./Flax/Common.hlsl"
#include "./Flax/Math.hlsl"
#include "./Flax/Octahedral.hlsl"

DDGI.shader file have these:
#include "./Flax/Common.hlsl"
#include "./Flax/Math.hlsl"
#include "./Flax/Quaternion.hlsl"
#include "./Flax/GlobalSignDistanceField.hlsl"
#include "./Flax/GI/GlobalSurfaceAtlas.hlsl"
#include "./Flax/GI/DDGI.hlsl"

If you have any of these shaders connected to your Bloom, then this issue could be somewhere there, maybe.

**Comment by mafiesto4** [comment]
Using Bounce Intensity with `1.5` means that each light bounce will get 50% additional more light which is physically inaccurate and will always flood such room with brightness. In general, smaller values like `1.1` will improve GI bounce without hurting lighting calculations. This slider is especially important since DDGI uses Global Surface Atlas which is inaccurate (software tracing, not hardware raytracing) and sometimes leaves black spots in world representation (due to no information about surface color/properties) so adding a little GI boost helps to mitigate it. Of course it can be used to reduce GI boost in certain scenes.

If you want to boost GI without this light explosion, then use `Intensity` under `GI` section.
