### ISSUE TITLE
3rd wheel and higher collider does not set correctly

### ISSUE THREAD

**Issue by gaberilde** [FlaxEngine/FlaxEngine#2379]
**Issue description:**

Setting 3rd wheel collider or above gliches back and actually sets it to first one instead

**Steps to reproduce:**

Add 3 wheels and try to set collider for 3rd wheel

**Minimal reproduction project:**

Dosent matter it happens for all projects

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
@RuanLucasGD would you mind looking into this issue?

**Comment by RuanLucasGD** [comment]
@mafiesto4  #2192  must sort the wheels to the correct index. It's a Physx requirement.

**Comment by Tryibion** [comment]
Instead of sorting the actual `_wheels` array here <https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Physics/PhysX/PhysicsBackendPhysX.cpp#L3454-L3474> could you sort the local `wheels` array here <https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Physics/PhysX/PhysicsBackendPhysX.cpp#L3505>

**Comment by mafiesto4** [comment]
I did a quick test and it works fine. I'll update https://github.com/FlaxEngine/FlaxSamples/tree/master/PhysicsFeaturesTour to include a car. Meanwhile you can graf a car prefab from a docs website: https://docs.flaxengine.com/manual/physics/vehicles.html#car-template

https://github.com/user-attachments/assets/5d379bab-de36-4dfe-a1da-e1ed38d451b6
