### ISSUE TITLE
Some weird lighting / shadow bug 

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2387]
**Issue description:**

There is some weird lighting bug(?). The brown color comes from the Additive Color of the SkyLight. If I change that to black, the weird tiles will be black. I have also tested it with some larger static models where I have the same behavior.

If i disable the "Sky" Actor, then everything turns brown. It looks like the Sky actors' lighting information is somehow missing in these GI "chunks," or idk how to call it.

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/2df952b6-abca-4557-90af-3bbd12f690f7

https://github.com/FlaxEngine/FlaxEngine/assets/14238126/4f74cf06-857f-4cd9-9f88-b62fa27ff753

**Steps to reproduce:**

1. Open attached project
2. Open Scene `Content/Scenes/MainScene`
3. Hit play
4. Move with A/D left/right in the edges you can see the brown stuff
5. You can also see it with the scene view. At a certain distance all will be brown.

**Minimal reproduction project:**

[Undercrop.zip](https://github.com/FlaxEngine/FlaxEngine/files/14827768/Undercrop.zip)

**Flax version:**

**Comment by mafiesto4** [comment]
That's because DDGI places probes only around the scene geometry - defined by GlobalSDF which is used to perform software raytracing. If you enable probes debug you will see this:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/b787b05b-6252-48d9-852e-c37b253a48f7)

And the probes are placed only around player capsule:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/39a7a420-fefc-4190-a20b-6931209617a1)

Docs: https://docs.flaxengine.com/manual/graphics/models/sdf.html

Solution is to build SDF for those block meshes:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/3fd89c60-d803-4354-a0df-35463aa56b1a)

Then scene looks like this:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/1b87e07c-4435-4a12-8b1e-e45457116c1f)
