### ISSUE TITLE
Strange Values with InputAxis

### ISSUE THREAD

**Issue by schmidt-florian** [FlaxEngine/FlaxEngine#2393]
**Issue description:**

The Raw Value looks fine, but the "Value" does return some strange values.

I get these readings:
```
[ 00:00:10.586 ]: [Info] Horizontal: Value: 0,083334506 Raw: 1
[ 00:00:11.323 ]: [Info] Horizontal: Value: 0,9833334 Raw: 0
[ 00:00:12.288 ]: [Info] Horizontal: Value: -0,083334 Raw: -1
[ 00:00:13.172 ]: [Info] Horizontal: Value: -0,9833336 Raw: 0
```

with this Script:

```
public class InputTest : Script
{
    private readonly InputAxis _axis = new InputAxis("Horizontal");

    public override void OnStart()
    {
        base.OnStart();
        _axis.ValueChanged += OnAxisChanged;
    }

    private void OnAxisChanged()
    {
        Debug.Log($"Horizontal: Value: {_axis.Value} Raw: {_axis.ValueRaw}");
    }
}
```

These are the Settings of the Input:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/14238126/f0ea9102-81ba-44f3-a40e-3dda0a126ca7)

there is nothing that explains these strange Values.

The values are produced by pressing A/D keys. There is no Gamepad connected to this PC.

**Steps to reproduce:**

1. Copy the script into a new project.
2. Press play and then A/D to view the values.

**Flax version:**

1.8

**Comment by mafiesto4** [comment]
`Value` is using input smoothing (controlled via `Sensitivity`, `Gravity` and `Scale`) so it takes 1-2 frames until that value reaches the `RawValue` which gives nice input smoothing for gameplay (can be controlled in Input settings per-axis).

But there was a bug with that input axis value change event which is fixed in: a1745e25a1de226901b1d307da270f8230cce8c0.
