### ISSUE TITLE
[Usability Request] Cache the lasted mesh used by the mesh on the animation editor

### ISSUE THREAD

**Issue by MrCapy0** [FlaxEngine/FlaxEngine#2508]
**Issue description:**
Each time that i need to open an animation i need to re-select the same mesh. Pls it's possible cache the last mesh used by the animation ?

**Steps to reproduce:**

https://github.com/FlaxEngine/FlaxEngine/assets/167662176/429f6867-0344-42f2-a36e-d4c00ebc97a9

**Flax version:**
1.8.1

**Comment by Menotdan** [comment]
For reference, the mesh used does get saved for animation graphs, its an actual part of the data in the graph and changing it will mark the graph as modified. I think it's this way right now because you don't apply an animation to a skinned model actor, but an animation graph. It definitely could be added though if you use it a lot

**Comment by mafiesto4** [comment]
Added in acd338981c68ffe74fcc44835a58be054c15844d.
