### ISSUE TITLE
[bug] can't disconnect from node if input is disabled

### ISSUE THREAD

**Issue by Zode** [FlaxEngine/FlaxEngine#2611]
https://github.com/FlaxEngine/FlaxEngine/assets/9205294/11b7cfea-965c-4517-a8b9-04e289fc6a8f

**Issue description:**
Can't disconnect from a node input if the input disables itself, expected behavior would be to allow to disconnect (and possibly connect) no matter what state the input is in. This may also affect output side of things also.

**Steps to reproduce:**
Connect to an input, and then swap material type so that the input becomes disabled.

**Flax version:**
1.8.6511.1

**Comment by Chikinsupu** [comment]
@mafiesto4 i could fix this - should be pretty straight forward. But for that i need to know the expected behaviour.

A) Should the ports on the material nodes all be interactable no matter what? So that even when a port is disabled you can disconnect from the port by dragging.
Alternatively: Only allow disconnecting on disabled ports, but not connecting.

or

B) Should the connection automatically disconnect when the port gets disabled


Btw. I just realized you can also right click on a disabled box and click on "remove all connection to that box". When this is intended behaviour then i assume A should be the fix.

**Comment by mafiesto4** [comment]
@Chikinsupu I think a right-click menu with an option to remove connections to that box + middle-mouse-click to remove that connection should be enough for this case.

**Comment by Chikinsupu** [comment]
> @Chikinsupu I think a right-click menu with an option to remove connections to that box + middle-mouse-click to remove that connection should be enough for this case.

then this issue can be closed, no? Since you can right click already, i haven't tested middle mouse button. Will check that later

**Comment by Zode** [comment]
> @Chikinsupu I think a right-click menu with an option to remove connections to that box + middle-mouse-click to remove that connection should be enough for this case.
I think this is horrible UX, and would throw off anyone coming from any other node graph based software like substance or even unity. Why not have the option to be able to rewire the connection while its connected to a disabled input/output?

**Comment by mafiesto4** [comment]
Then it would be good to add reconnecting ability for disabled connections too.

**Comment by Chikinsupu** [comment]
Okay, so i have done a bit of research of how some other engines and programs handle this. 
One thing flax does different to a lot of other tools is, that it just disables ports that don't contribute to the material where as other engines and tools straight up remove the ports.

In Blender the port gets removed and the connection gets deleted. But when the port appears again it instantly reconnects.
![EXBlender](https://github.com/FlaxEngine/FlaxEngine/assets/6757167/29aa42c3-43e9-4a24-b89f-0a3a3999ea16)

In Amplify the port gets removed and the connection gets deleted and it stays that way
![EXAmplify](https://github.com/FlaxEngine/FlaxEngine/assets/6757167/be4c6aae-da72-4836-a3c0-287afbddea92)

In Unity itself its a bit special. Unity also removes its ports, except when they had a connection, then they get disabled like in flax.
But Unity actually lets you freely interact with disabled ports. I can change the connections and even just delete them as i wish.
![EXUnity](https://github.com/FlaxEngine/FlaxEngine/assets/6757167/8a7c4d38-26d4-41c0-a95c-52def2d439a9)

In Godot there aren't any disabled ports whatsoever, so nothing there.
And i don't have things like unreal or substance installed rn, so no insights there.

@mafiesto4 : So when i understand correctly, from your previous comments then we want a similar behaviour to blender (minus removing the port), is that correct? I mean in order to accomplish that we can simple just not render the connection to disabled ports.

UX wise i am actually a fan of Unitys approach, where you are just free to do whatever you want, it's not like it's gonna break anything.

Can i get your input to this one last time and then i will look into this issue and create a PR

**Comment by Chikinsupu** [comment]
Yeah, for now i just did it the unity way without hiding the port in #2649
I might build upon this in the future and make ports appear/disappear when they are no longer in use, like the blender example.
