### ISSUE TITLE
[BUG] AssetReference serialization is incompatible between C# and C++

### ISSUE THREAD

**Issue by Vizepi** [FlaxEngine/FlaxEngine#2711]
**Issue description:**
When an asset is serialized by C# then loaded from C++ (or vice-versa) the asset references are broken.  
The investigations I did on this issue can be found here: https://discord.com/channels/437989205315158016/538664104856911883/1251525803032711240

**Steps to reproduce:**
- Open the provided project
- Open the scene Project/Content/scene
- Press Play
- Observe the log

**Minimal reproduction project:**
[Project.zip](https://github.com/user-attachments/files/15857228/Project.zip)

**Flax version:**
1.8.2

**Host:**
Windows 11
Laptop Acer Nitro V 15 (ANV15-51-754J)

**Comment by Vizepi** [comment]
This issue is probably extended to all serialized asset reference types (AssetReference, WeakAssetReference, ScriptingObjectReference, SoftObjectReference, SoftAssetReference...)

**Comment by mafiesto4** [comment]
Similar issue to #2774. Fixed in 7a89e78f4395cc459f7e53270d56bfaf45ffb522 but it will require to re-save faulty json assets. C#-side serialization was wrong and didn't match C++ deserialization logic.

Also, in ec412d9be0b1343e443af202cc8672272804da28 I added improvement for editor undo/redo of those properties.
