### ISSUE TITLE
Bug with Packed Vector and Vector Parameters in Animation Graph (Possibly elsewhere)

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#272]
**Issue description:**
Using a value from a Vector3 Parameter with a Packed Vector doesn't work in the Animation Graph.
![image](https://user-images.githubusercontent.com/35228400/108643467-d3de2b80-74fe-11eb-9949-76552dcac52c.png)

**Steps to reproduce:**
This is way too difficult to prove using a bunch of steps. I've made a video that goes through all the steps to create this bug. This bug was driving me insane for ages.

https://drive.google.com/file/d/1xwQsYZmG8LBryeonFCoflnzjB_Ybfc9r/view?usp=sharing

**Comment by SilentCLD** [comment]
I ran into this issue when trying to use a parameterized Vector2 as an input into a `Multi Blend 2D` node.
The problem seems to be with `AnimGraphExecutor::ProcessGroupParameters` returning the actual value (Vector2 in this case) instead of going further into the node to get the X or Y float value.
Currently this works fine for any type with one output (int, bool, float, string etc..) but breaks as soon as multiple outputs are present (Vector2/3/4, Color, Matrix, etc..).
https://github.com/FlaxEngine/FlaxEngine/blob/c3e3e70f96413598e407a899a7c8c327cb6ab8b0/Source/Engine/Animations/Graph/AnimGroup.Animation.cpp#L444-L460

.
If we look at `VisjectExecutor::ProcessGroupConstants` we can see that the value returned is based on `box->ID` so I guess something similar needs to happen for parameters?
https://github.com/FlaxEngine/FlaxEngine/blob/c3e3e70f96413598e407a899a7c8c327cb6ab8b0/Source/Engine/Visject/VisjectGraph.cpp#L51-L61

**Comment by mafiesto4** [comment]
Sorry for late response here. @SilentCLD detected the problem location correctly. Fixed here: 922201d1c03f9b96f6a334a4a5e73fa0b349ac47.
