### ISSUE TITLE
[Bug] Bindings generator: MAX_ macros not converted for enum values

### ISSUE THREAD

**Issue by WolfInABowl** [FlaxEngine/FlaxEngine#2867]
**Issue description:**
When using the MAX_ macros as values for an API_ENUM, e.g.
```cpp
API_ENUM() enum FooEnum : uint8
{
    Foo = MAX_uint8,
    Bar,
};
```
The bindings generator doesn't convert it to the C# equivalent, producing invalid code.
```cs
//Generated code, will not compile
[Unmanaged]
public enum FooEnum : byte
{
    Foo = MAX_uint8,
    Bar,
}
```
This is handled correctly in other cases, such as when assigning the default value of an API_FIELD:
```cpp
API_FIELD() byte Foo = MAX_int8;
```
```cs
//Generated code, macro is converted properly
[Unmanaged]
[DefaultValue(sbyte.MaxValue)]
public byte Foo
{
    get { return Internal_GetFoo(__unmanagedPtr); }
    set { Internal_SetFoo(__unmanagedPtr, value); }
}
```

**Flax version:**
1.8+

**Comment by Tryibion** [comment]
For the case of using MAX_int8 in enums, how to handle the case of enum values after the value that equals MAX_int8? because in c# the values will fail to compile due to no next available number to set the next value to. 

For example:
```
API_ENUM() enum class TestingCppEnum : uint8
{
     Testing1,
     Testing2 = MAX_uint8,
     Testing3,
     Testing4
}
```
This will error out on Testing3 and Testing4 if the MAX_uint8 is converted to byte.MaxValue because there are no available values to move it to. Now someone could add Testing3 = 0, but then there is a conflict in c# with Testing1 and Testing3 both being the value of 0. I guess it could loop through and find the next available value, but I am not sure what implications that could have transferring the value between c# and c++. Maybe that has to just be a limitation of the system that using a MAX would have to be at the end of an Enum?
