### ISSUE TITLE
Three more UI Bugs (Ordering, Auto-width, and Anchor)

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#312]
**Issue description:**
![image](https://user-images.githubusercontent.com/35228400/110238345-463a1b80-7f95-11eb-856d-28ddbbfc8339.png)

Three UI Bugs
1. Draw Order of UI Elements doesn't appear right.
2. Auto-width and Auto-Height don't seem to affect parent sprite which results in text getting cut.
3. Anchor's sometimes seem to break the entire viewer.

**Steps to reproduce:**
To expose these three bugs, simply follow the steps in this film:
https://drive.google.com/file/d/1A4NLk9PpiK0-fhxN_8q8S4MjCleTn6Wu/view?usp=sharing

**Flax version:**
Branch 1.1

**Comment by stefnotch** [comment]
Regarding 1., apparently, while an image is a container control, it first draws the background *and children* and then draws itself
https://github.com/FlaxEngine/FlaxEngine/blob/b8d03636dcda9a2703805ca99412dd2328f93ad2/Source/Engine/UI/GUI/Common/Image.cs#L85

The correct order would probably be: background, image, children

**Comment by jb-perrier** [comment]
Image order issue fixed by #355 .

**Comment by mafiesto4** [comment]
1. Fixed by #355
2. The auto-width/auto-height affect the label size only, not the parent container. Using horizontal/vertical panels can be used to arrange parent control based on child control dimensions.
3. Fixed in 5c171c8b585580b34a304242d0163407b1948b16

*note: the longer text will be clipped by the label by default due to **Clip Children**, it can be disabled to show the label text outside the parent image bounds.
