### ISSUE TITLE
Long term: switch to .NET 5/6/7

### ISSUE THREAD

**Issue by HydrogenC** [FlaxEngine/FlaxEngine#395]
The . NET  FW no longer supports new language and library features, while mono is quite poor in performance, especially when Interoping. The unified .NET platform brings new language features with significant performance boosts. Since . NET 6 will be a LTS release, I wish some day the engine can support . NET 6 as the scripting engine.

**Comment by mafiesto4** [comment]
There is a plan to update to the latest Mono this year for C# 8/9. But other changes are harder to tackle since we need to keep C# proper support for all platforms we have (eg. AOT with LLVM on consoles has great perf in Mono).
Also, Microsoft won't drop Mono support as it's used as Mono VM to run on mobile (iOS/Android as Xamarin).

**Comment by HydrogenC** [comment]
> Also, Microsoft won't drop Mono support as it's used as Mono VM to run on mobile (iOS/Android as Xamarin).

Maybe it will be merged into CoreCLR, since mobile support for iOS and Android is added in . NET 6.

**Comment by LCRW** [comment]
Unlikely mono will be merged, due to its licence, more probable is mono being kept up to date since the original dev of mono works for microsoft and they also invest in to mono through .Net Foundation. The stats on performance increases are not that meaningful, since mono has not released a version that utilises .Net 5 yet although it is in the works. A comparison between mono using new .Net and CoreCLR is needed for accurate assessment since most of the improvements have gone in to the Mashalling area, those improvements will be seen by an updated mono also.
It's worth mentioning that Flax does not use P/Invoke as its interop mechanism, but uses a faster method.

**Comment by HydrogenC** [comment]
> Unlikely mono will be merged, due to its licence, more probable is mono being kept up to date since the original dev of mono works for microsoft and they also invest in to mono through .Net Foundation. 
That's correct. But now mono is becoming a part of the core runtime to run mobile apps. My idea is to include the whole core runtime instead of just mono. The compiler of mono doesn't even support C# 7 fully.

**Comment by LCRW** [comment]
Maybe so, but Flax utilises features in mono that are unavailable in the CoreCLR, ie VTable access. This is not likely to ever happen, neither is Sony allowing CoreCLR to run on their console platforms likely to happen anytime soon. In order to allow for a full migration you would need to write your own CLR host handler and re-implement the VTable hack that mono provides, allowing fallback to mono for platforms that need it.

**Comment by HydrogenC** [comment]
> Maybe so, but Flax utilises features in mono that are unavailable in the CoreCLR, ie VTable access. This is not likely to ever happen, neither is Sony allowing CoreCLR to run on their console platforms likely to happen anytime soon. 

That makes sense.

**Comment by GoaLitiuM** [comment]
A lot of progress has been done in the [dotnet7](https://github.com/FlaxEngine/FlaxEngine/tree/dotnet7) branch already for .NET 7 support (currently runs on Windows only).

**Comment by mafiesto4** [comment]
Yeah, we're switching to .Net 7 in Flax 1.6.

**Comment by atcarter714** [comment]
> A lot of progress has been done in the [dotnet7](https://github.com/FlaxEngine/FlaxEngine/tree/dotnet7) branch already for .NET 7 support (currently runs on Windows only).

Music to my ears, I just started assessing Flax for how suitable it would be for us and was concerned about the deprecated runtimes and not being on at least .NET 6 LTS minimum ... I am only building for Windows/UWP pretty much anyways and by the time I'm thinking of publishing anything I'm sure the other platforms would be supported by then anyway and Flax version number will have incremented a bit ... so now it seems like it's probably worth the time to make a fork or clone of the engine and start digging in ...
