### ISSUE TITLE
Add support for double precision floats

### ISSUE THREAD

**Issue by aaronfranke** [FlaxEngine/FlaxEngine#56]
Double-precision floats are necessary for games that take place on extremely large scales, such as in the vastness of space. There are workarounds, but they all come with issues. If Flax Engine wishes to support extremely large scales, it would make sense to add support for double precision floats.

For further justification on this feature, please see this proposal I made for Godot: https://github.com/godotengine/godot-proposals/issues/892

As for the implementation, it is possible to support compiling with both single and double precision floats at the same time, if done correctly. This can be handled in C# via preprocessor directives by defining an alias, like this:

```cs
#if REAL_T_IS_DOUBLE
using real_t = System.Double;
#else
using real_t = System.Single;
#endif
```

The downside is that this alias definition must be repeated in every C# file. For a more detailed example, see this file in Godot: https://github.com/godotengine/godot/blob/master/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector3.cs

**Comment by mafiesto4** [comment]
Added to the `master`! Can be enabled in a custom engine build by setting this to `true`: 

https://github.com/FlaxEngine/FlaxEngine/blob/18cd7b657e4ccbe21ab46bc90b30df1ca0c47ae6/Flax.flaxproj#L13

Soon there will be proper support for the rendering relative to the camera (work in progress) and implementation of 64-bit coordinates in other systems (audio, physics,..). Then, of course we will add documentation.

By setting `UseLargeWorlds=true` the `Vector2/3/4` types are using `double` instead of `float`:

* C++
https://github.com/FlaxEngine/FlaxEngine/blob/18cd7b657e4ccbe21ab46bc90b30df1ca0c47ae6/Source/Engine/Core/Types/BaseTypes.h#L93-L124

* C#
https://github.com/FlaxEngine/FlaxEngine/blob/18cd7b657e4ccbe21ab46bc90b30df1ca0c47ae6/Source/Engine/Core/Math/Vector3.cs#L1-L5

We do have vector types `Float2/3/4`, `Double2/3/4` and `Int2/3/4` to explicitly use certain precision and data size.
