### ISSUE TITLE
Mesh severally deformed with imported animation

### ISSUE THREAD

**Issue by AnthonyPython** [FlaxEngine/FlaxEngine#564]
**Issue description:**
Importing my animation severally deforms the arms.
(note: importing the animation as a fbx only imported as 1 frame)

**Steps to reproduce:**
Import fps arms(fbx), Import animation(glb)(or fbx), hook up animation in a animation graph.

**Minimal reproduction project:**
Attached.
[fps_arms.zip](https://github.com/FlaxEngine/FlaxEngine/files/6765942/fps_arms.zip)

**Flax version:**
1.1.6218

**Comment by mafiesto4** [comment]
Could you share the original fbx files? So we could fix the importer. Probably problem related to invalid bind pose in the skinned model:
![image](https://user-images.githubusercontent.com/3464853/125062375-9c87aa00-e0ae-11eb-90af-18bfa908f523.png)

(I guess animation is fine, just bind pose matrix is invalid)

**Comment by AnthonyPython** [comment]
I believe maybe there is a problem with animation as well, my animation only had 33 frames but when imported it had many more frames and was very slow it has 1100 frames which isn't possible that is with the .glb, with the .fbx version only one frame gets imported. I have attached the arms fbx, the .glb animation, and .fbx for you to look at.
[fps_testing_source.zip](https://github.com/FlaxEngine/FlaxEngine/files/6793217/fps_testing_source.zip)

**Comment by mtszkarbowiak** [comment]
Right at the beginning, I want to point out that I could not check if the cause of OP's problems is the same as mine. I believe that the title of the bug should be:

**Animated _Skinned Model_ has vertex displacement applied treating non-displaced vertices as vertices displaced by the first frame of animation.**

# Producing

Flax version is 1.3. I created a model in Blender with simple running animation and exported using FBX. I imported the FBX 2 times: First time as *Skinned Model*, second as *Animation* according to the documentation.

Previewing animation with *Preview Model* set to corresponding model shows corrupted animation. The bug occurs also in Animation Graph and the game itself.

To check if it wasn't my fault I tried the same FBX in different engine and it worked perfectly fine there.

# My suspicion

I suspect the cause of the bug is that FBX importer treats first frame of animation as not-animated displacement, which is not true. I attached screenshots of 2 frames of animation to show my point.

First frame of walking animation, being T-pose (invalid):

![image](https://user-images.githubusercontent.com/69864511/186768234-f945c7f6-e923-43f9-a087-737fd0f3b678.png)

Severely deformed mesh:

![image](https://user-images.githubusercontent.com/69864511/186768403-3e1f37e5-dbcb-48bb-9a9e-1f083480f117.png)

Reference in Unity:

![image](https://user-images.githubusercontent.com/69864511/186769000-e60b9b46-1b2c-432b-b60f-eb428bd3cc28.png)

**Comment by mafiesto4** [comment]
That has been fixed (after 2 years xD) as a part of #1525.

**Comment by mafiesto4** [comment]
![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/888542e1-c93c-4444-931d-396057d891f1)

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/63aec53f-d8ba-4daa-8aac-2e3faf258e9b
