### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ANTEVETY** [FlaxEngine/FlaxEngine#597]
In my opinion, memory is slowly leaking in the engine and does not stop. It doesn't matter if the editor is minimized or not. 

![ScreenShot_20210812184306](https://user-images.githubusercontent.com/8769199/129201043-13d222f3-f027-423c-b56b-13c2187ea1e2.jpg)
After 5min
![ScreenShot_20210812185002](https://user-images.githubusercontent.com/8769199/129201126-d60c6eb3-aa1a-46c4-a76e-e1e479eab120.jpg)

Steps to reproduce:
An empty scene was opened (Startup Scene Mode: None)

Flax version:
1.2.6223

**Comment by NotHyper-474** [comment]
Tested a little bit with an empty scene with only a camera and minimized editor, after around 17 minutes memory usage went from around 200 MB to this
![image](https://user-images.githubusercontent.com/40342021/129232602-93c677de-72ce-4ba5-959c-2287c2b06486.png)
After 1 hour it went up to 1 GB
![image](https://user-images.githubusercontent.com/40342021/129240003-983f265e-2260-4864-b370-2dc44d70b972.png)
So there really must be some kind of memory leak.

Flax version:
1.2.6223

**Comment by mafiesto4** [comment]
The source of this leak is Tracy profiler that was allocating memory for profiler events. I changed the source location events policy to use static entry and prevent this leak. The negative outcome of this is that Tracy cannot be connected to the Editor if game code uses C++ profile events and there was a hot-reload of code.
Fixed in: bc634e9d377bee90025f54c7224b4fee460c3928

**Comment by NewNodeGames** [comment]
In 1.2.6223 version even closing the active scene the editor eats more than 2 GB ram. Is solved on the development build? Flax works pretty well on low end hardware anyway, it enters to play mode instantly. Unity an others are turtles in comparison.
