### ISSUE TITLE
Setting Icon on settings, does not set Icon in cooked application

### ISSUE THREAD

**Issue by Tryibion** [FlaxEngine/FlaxEngine#928]
Set Icon. cook game for windows. The set Icon is just the Flax Icon and it still calls it FlaxGame as instead of the product name.

![image](https://user-images.githubusercontent.com/71274967/216735288-0b8e977a-c68f-4bf3-acf9-4a44926e7fca.png)

![image](https://user-images.githubusercontent.com/71274967/216735302-2a7289ee-3da0-4123-81dc-8629a5edb0ca.png)

**Flax version:**
1.5.6336

**Comment by mafiesto4** [comment]
It might be case when Windows Explorer decides to cache the icon for an executable file and the incremental build fails to update it. Anyway, we need to fix/improve this.

**Comment by Tryibion** [comment]
I did a quick browse of the code and I dont really see where the windows build is using the product name instead of `FlaxGame` for windows... Shouldn't the name of the .exe be changes to the product name?

**Comment by mafiesto4** [comment]
> Shouldn't the name of the .exe be changes to the product name?

It could be if we would use separate `FlaxEngine.dll` with engine and `exe` would just launch the app or if game doesn't;t use C++ scripting because otherwise C++ modules are linked against `FlaxEngine.dll` and use it. Maybe there is another way to handle this. (`GameTarget.Build.cs` can use `Monolithic` link mode to output a single `exe` with whole gamecode)

**Comment by Tryibion** [comment]
Ah, I like either Idea, It would be nice to have the `exe` be named the product name because then when publishing it is less confusing (Like linking to steam without my own page, it just calls all my apps flax game and it is hard to tell which is which).

**Comment by mafiesto4** [comment]
Should be fixed in c67d352065c6b0b1e431816ed3b353c18a069ea5. Keep in mind that Windows Explorer caches icons so if you change the icon in game settings and run and build the icons might be still old. Copying file to other folder shows the difference.

In case, the issue occurs again please attach the source icon file (easier to fix for specific issue).
