### ISSUE TITLE
`NetworkReplicator::AddObject` is counterintuitive 

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#973]
Current implementation of `NetworkReplicator::AddObject` operates under principle that you first need to call `NetworkManager::StartClient/Host/Server()`, and only then can you register objects for replication. This process is not only not reflected anywhere in the documentation, but also begs to ask more questions, like: 

* Why cant we simply register replicated objects and THEN start client/server? Wouldn't that be more intuitive? 
* What is going to happen to the client that would first connect to the server, and then start loading some scene with semi-persistent objects (like doors) that would self register themself in `OnStart` function for replication? 
* When would the server first try to sync state after the initial connection and what is the time frame for the game to register all of the replicated objects in time for their first sync from the server?

These and other questions could in fact be answered by either providing a clearer explanation into how and `when` to register objects that not only come from dynamically spawned nature (like in Arizona, it only explains how to handle players and that's it), or by allowing to first register replicated objects and `then` start the networking layer.

**Comment by alec1o** [comment]
I have this question too!

**Comment by mafiesto4** [comment]
1) `NetworkReplicator` APIs are ignored when `NetworkManager` is offline but I guess for `AddObject` we could cache calls and reply them when server/client goes online. The design decision behind is that usually, game has a main menu level with network connection stuff (eg. via online platform lobbies like Xbox/PSN/Steam), and then once players in lobby are ready and game servers starts everyone can connect via `NetworkManager` and load the game level.
As a workaround, if you want to start the network immediately you can reload scene or write a GamePlugin that would initialize and start network before scenes are loaded.

2) When the client loads the level each `static` object like doors can register itself via `NetworkReplicator::AddObject` which gonna happen on all clients and server (object ID is the same - from scene asset) thus you can send RPCs or replicate that object easily. By default, objects are owned by server so only server will be able to change replicated properties of that object (eg. door open state) but server can change the owner or replication info for object (eg. via `NetworkReplicator.SetObjectOwnership`).

3) Right now, the server will send the first replication data right after new client connects but since it's all about networking thus there always will be some delay or untraceable lag. In Flax 1.5 replicated objects are updated and sent every frame (by the owner, usually server). For Flax 1.6 there will be added (soon) **Network Replication Hierarchy** which will allow to configure data send-rate per object or per-group of objects.
Also, for example, Arizona Framework waits until Player State, Player Pawn, and Player Controller objects are spawned and replicated before issuing a player spawn event for gameplay so it depends on several objects' initialization to be finished. Maybe we could add some systematic feature to wait for sync of a specific object(s) for gameplay to be ready.

Sorry for a late reply. I'll update docs with those explanations for the future.
